FROM node:22-alpine AS build
WORKDIR /app

COPY weather-client/package*.json ./
RUN npm ci

COPY weather-client/ .
RUN npm run build

FROM nginx:alpine
COPY weather-client/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
